# Generated by Django 5.0.3 on 2024-04-02 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neticapp', '0002_alter_invoice_invoice_user_alter_invoice_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
