# Generated by Django 5.0.3 on 2024-03-18 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neticapp', '0003_alter_order_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of_user', to=settings.AUTH_USER_MODEL, verbose_name='Order of user'),
        ),
    ]
