# Generated by Django 5.0.3 on 2024-04-02 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neticapp', '0003_alter_invoice_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
