# Generated by Django 5.0.3 on 2024-03-18 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neticapp', '0004_alter_order_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='neticapp.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, 'NotPaid'), (2, 'Partial'), (3, 'Paid')], default=1),
        ),
    ]
